[default]
verbosity = 5
sender = '0xaEd009c79E1D7978FD3B87EBe6d1f1FA3C542161'
solc_version = '0.8.10'
optimizer = true                                             
optimizer_runs = 200  


[ci]
verbosity = 5