[default]
verbosity = 1
# solc_version = '0.8.10'
auto_detect_solc = true
# offline = true
optimizer = true                                             
optimizer_runs = 200  
src = "src"
test = "test"


[ci]
verbosity = 5